const PC_MIN_WIDTH = 1200;
const TABLET_MIN_WIDTH = 768;
const MOBILE_MIN_WIDTH = 375;

export const SCREEN_SIZE = {
  PC_MIN_WIDTH,
  TABLET_MIN_WIDTH,
  TABLET_MAX_WIDTH: PC_MIN_WIDTH - 1,
  MOBILE_MIN_WIDTH,
  MOBILE_MAX_WIDTH: TABLET_MIN_WIDTH - 1,
} as const;
