import Head from 'next/head'
import Image from 'next/image'
import styles from '@/src/styles/Home.module.css'
import Header from './components/Header'
import BestPostList from './components/BestPostList'
import PostList from './components/PostList'

export default function board() {
  return (
    <>
      <Head>
        <title>판다마켓</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/icons/favicon.ico" />
      </Head>
      <Header></Header>
      <BestPostList></BestPostList>
      <PostList></PostList>
    </>
  )
}
