import Head from 'next/head';
import Image from 'next/image';
import BoardsLayout from '@/layouts/BoardsLayout';

export default function Home() {
  return (
    <>
      <Head>
        <title>판다 마켓 | 자유게시판</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="mx-auto max-w-[1200px] p-4 md:p-6">
        <BoardsLayout />
      </main>
    </>
  );
}
